name: Build Tarball

on:
  push:
    branche: [branchAutomake]
  pull_request:
    branches: [branchautomake]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Tarball file
      run: |
        autoreconf -i
        ./configure
        make dist
        
        
